jest.mock('services/PlayerRecord');

import playerRecordService from 'services/PlayerRecord';

export const mockTable = [
    {
        "year": 2010,
        "responses": 42,
        "P": 35,
        "W": 23,
        "D": 1,
        "L": 11,
        "points": 70,
        "averages": 2,
        "stalwart": 80,
        "pub": 28,
        "rank_points": 1,
        "rank_averages": 2,
        "rank_averages_unqualified": null,
        "rank_stalwart": 3,
        "rank_speedy": 11,
        "rank_speedy_unqualified": null,
        "rank_pub": 3,
        "speedy": 18825,
        "playerId": 49,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 47,
        "P": 31,
        "W": 16,
        "D": 1,
        "L": 14,
        "points": 49,
        "averages": 1.580645161290323,
        "stalwart": 70,
        "pub": 1,
        "rank_points": 2,
        "rank_averages": 5,
        "rank_averages_unqualified": null,
        "rank_stalwart": 7,
        "rank_speedy": 12,
        "rank_speedy_unqualified": null,
        "rank_pub": 12,
        "speedy": 23571,
        "playerId": 46,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 46,
        "P": 37,
        "W": 15,
        "D": 2,
        "L": 20,
        "points": 47,
        "averages": 1.27027027027027,
        "stalwart": 84,
        "pub": 27,
        "rank_points": 3,
        "rank_averages": 11,
        "rank_averages_unqualified": null,
        "rank_stalwart": 1,
        "rank_speedy": 4,
        "rank_speedy_unqualified": null,
        "rank_pub": 4,
        "speedy": 9865,
        "playerId": 11,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 39,
        "P": 30,
        "W": 15,
        "D": 2,
        "L": 13,
        "points": 47,
        "averages": 1.566666666666667,
        "stalwart": 68,
        "pub": 31,
        "rank_points": 3,
        "rank_averages": 7,
        "rank_averages_unqualified": null,
        "rank_stalwart": 8,
        "rank_speedy": 23,
        "rank_speedy_unqualified": null,
        "rank_pub": 2,
        "speedy": 79055,
        "playerId": 14,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 33,
        "P": 26,
        "W": 15,
        "D": 2,
        "L": 9,
        "points": 47,
        "averages": 1.807692307692308,
        "stalwart": 59,
        "pub": null,
        "rank_points": 3,
        "rank_averages": 4,
        "rank_averages_unqualified": null,
        "rank_stalwart": 9,
        "rank_speedy": 10,
        "rank_speedy_unqualified": null,
        "rank_pub": null,
        "speedy": 18661,
        "playerId": 30,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 44,
        "P": 36,
        "W": 15,
        "D": 2,
        "L": 19,
        "points": 47,
        "averages": 1.305555555555556,
        "stalwart": 82,
        "pub": null,
        "rank_points": 3,
        "rank_averages": 10,
        "rank_averages_unqualified": null,
        "rank_stalwart": 2,
        "rank_speedy": 8,
        "rank_speedy_unqualified": null,
        "rank_pub": null,
        "speedy": 17300,
        "playerId": 62,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 41,
        "P": 33,
        "W": 14,
        "D": 2,
        "L": 17,
        "points": 44,
        "averages": 1.333333333333333,
        "stalwart": 75,
        "pub": 2,
        "rank_points": 7,
        "rank_averages": 9,
        "rank_averages_unqualified": null,
        "rank_stalwart": 6,
        "rank_speedy": 15,
        "rank_speedy_unqualified": null,
        "rank_pub": 10,
        "speedy": 35192,
        "playerId": 31,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 39,
        "P": 19,
        "W": 13,
        "D": 2,
        "L": 4,
        "points": 41,
        "averages": 2.157894736842105,
        "stalwart": 43,
        "pub": 1,
        "rank_points": 8,
        "rank_averages": 1,
        "rank_averages_unqualified": null,
        "rank_stalwart": 12,
        "rank_speedy": 1,
        "rank_speedy_unqualified": null,
        "rank_pub": 12,
        "speedy": 3108,
        "playerId": 67,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 47,
        "P": 34,
        "W": 13,
        "D": 1,
        "L": 20,
        "points": 40,
        "averages": 1.176470588235294,
        "stalwart": 77,
        "pub": 34,
        "rank_points": 9,
        "rank_averages": 14,
        "rank_averages_unqualified": null,
        "rank_stalwart": 4,
        "rank_speedy": 13,
        "rank_speedy_unqualified": null,
        "rank_pub": 1,
        "speedy": 24418,
        "playerId": 12,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 42,
        "P": 34,
        "W": 13,
        "D": 1,
        "L": 20,
        "points": 40,
        "averages": 1.176470588235294,
        "stalwart": 77,
        "pub": 2,
        "rank_points": 9,
        "rank_averages": 14,
        "rank_averages_unqualified": null,
        "rank_stalwart": 4,
        "rank_speedy": 3,
        "rank_speedy_unqualified": null,
        "rank_pub": 10,
        "speedy": 9131,
        "playerId": 60,
        "gameDayId": 461,
    },
];

export const setupTableMocks = () => {
    beforeEach(() => {
        (playerRecordService.getTable as jest.Mock).mockResolvedValue(mockTable);
    });
};
