services:
  server:
    build:
      context: .
      secrets:
        - AZURE_TENANT_ID
        - AZURE_CLIENT_ID
        - AZURE_CLIENT_SECRET
        - AZURE_STORAGE_ACCOUNT_NAME
        - AZURE_STORAGE_CONTAINER_NAME
        - DATABASE_URL
        - BETTER_AUTH_SECRET
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - MICROSOFT_CLIENT_ID
        - MICROSOFT_CLIENT_SECRET
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    ports:
      - 3000:3000

  db:
    image: mariadb:lts
    restart: always
    secrets:
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

secrets:
  AZURE_TENANT_ID:
    environment: AZURE_TENANT_ID
  AZURE_CLIENT_ID:
    environment: AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET:
    environment: AZURE_CLIENT_SECRET
  AZURE_STORAGE_ACCOUNT_NAME:
    environment: AZURE_STORAGE_ACCOUNT_NAME
  AZURE_STORAGE_CONTAINER_NAME:
    environment: AZURE_STORAGE_CONTAINER_NAME
  MYSQL_ROOT_PASSWORD:
    environment: MYSQL_ROOT_PASSWORD
  DATABASE_URL:
    environment: DATABASE_URL_DOCKER
  BETTER_AUTH_SECRET:
    environment: BETTER_AUTH_SECRET
  GOOGLE_CLIENT_ID:
    environment: GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET:
    environment: GOOGLE_CLIENT_SECRET
  MICROSOFT_CLIENT_ID:
    environment: MICROSOFT_CLIENT_ID
  MICROSOFT_CLIENT_SECRET:
    environment: MICROSOFT_CLIENT_SECRET

volumes:
  db_data:
