module.exports = {
    automock: false,
    collectCoverage: true,
    coverageDirectory: 'coverage',
    coveragePathIgnorePatterns: ['/node_modules/'],
    coverageProvider: 'v8',
    projects: [
        {
            displayName: { name: 'api', color: 'yellow' },
            clearMocks: true,
            moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
            moduleNameMapper: {
                '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
                '^actions/(.*)$': '<rootDir>/src/actions/$1',
                '^api/(.*)$': '<rootDir>/src/app/api/$1',
                '^components/(.*)$': '<rootDir>/src/components/$1',
                '^environment/(.*)$': '<rootDir>/src/environments/$1',
                '^lib/(.*)$': '<rootDir>/src/lib/$1',
                '^mocks/(.*)$': '<rootDir>/src/mocks/$1',
                '^prisma/(.*)$': '<rootDir>/prisma/$1',
                '^prisma/generated/schemas$': '<rootDir>/prisma/generated/schemas.ts',
                '^server-only$': '<rootDir>/tests/__mocks__/server-only.ts',
                '^services/(.*)$': '<rootDir>/src/services/$1',
                '^tests/(.*)$': '<rootDir>/tests/$1',
            },
            modulePaths: ['<rootDir>/src/'],
            setupFilesAfterEnv: ['<rootDir>/jest.setup.backend.ts'],
            testEnvironment: 'node',
            testMatch: ['<rootDir>/**/api/**/*.test.ts'],
            testPathIgnorePatterns: ['/node_modules/', '/e2e/'],
            transform: {
                '^.+\\.(t|j)sx?$': ['@swc/jest'],
                '^.+\\.css$': 'jest-css-modules-transform'
            },
            transformIgnorePatterns: [
                "node_modules/(?!(nanostores|better-auth|uncrypto|jose|@noble)/)",
            ],
            watchPathIgnorePatterns: [
                "<rootDir>/.git/",
                "<rootDir>/.github/",
                "<rootDir>/.next/",
                "<rootDir>/.vscode/",
                "<rootDir>/build/",
                "<rootDir>/coverage/",
                "<rootDir>/dist/",
                "<rootDir>/node_modules/",
                "<rootDir>/out/",
                "<rootDir>/src/tests/components/",
                "<rootDir>/src/tests/services/",
            ],
        },
        {
            displayName: { name: 'services', color: 'magenta' },
            clearMocks: true,
            moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
            moduleNameMapper: {
                '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
                '^actions/(.*)$': '<rootDir>/src/actions/$1',
                '^api/(.*)$': '<rootDir>/src/app/api/$1',
                '^components/(.*)$': '<rootDir>/src/components/$1',
                '^environment/(.*)$': '<rootDir>/src/environments/$1',
                '^lib/(.*)$': '<rootDir>/src/lib/$1',
                '^mocks/(.*)$': '<rootDir>/src/mocks/$1',
                '^prisma/(.*)$': '<rootDir>/prisma/$1',
                '^prisma/generated/schemas$': '<rootDir>/prisma/generated/schemas.ts',
                '^server-only$': '<rootDir>/tests/__mocks__/server-only.ts',
                '^services/(.*)$': '<rootDir>/src/services/$1',
                '^tests/(.*)$': '<rootDir>/tests/$1',
            },
            modulePaths: ['<rootDir>/src/'],
            setupFilesAfterEnv: ['<rootDir>/jest.setup.backend.ts'],
            testEnvironment: 'node',
            testMatch: ['<rootDir>/**/services/**/*.test.ts'],
            testPathIgnorePatterns: ['/node_modules/', '/e2e/'],
            transform: {
                '^.+\\.(t|j)sx?$': ['@swc/jest'],
                '^.+\\.css$': 'jest-css-modules-transform'
            },
            transformIgnorePatterns: [
                "node_modules/(?!(nanostores|better-auth|uncrypto|jose|@noble)/)",
            ],
            watchPathIgnorePatterns: [
                "<rootDir>/.git/",
                "<rootDir>/.github/",
                "<rootDir>/.next/",
                "<rootDir>/.vscode/",
                "<rootDir>/build/",
                "<rootDir>/coverage/",
                "<rootDir>/dist/",
                "<rootDir>/node_modules/",
                "<rootDir>/out/",
            ],
        },
        {
            displayName: { name: 'components', color: 'blue' },
            clearMocks: true,
            moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node', 'mjs'],
            moduleNameMapper: {
                '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
                '^actions/(.*)$': '<rootDir>/src/actions/$1',
                '^api/(.*)$': '<rootDir>/src/app/api/$1',
                '^components/(.*)$': '<rootDir>/src/components/$1',
                '^environment/(.*)$': '<rootDir>/src/environments/$1',
                '^lib/(.*)$': '<rootDir>/src/lib/$1',
                '^mocks/(.*)$': '<rootDir>/src/mocks/$1',
                '^prisma/(.*)$': '<rootDir>/prisma/$1',
                '^prisma/generated/schemas$': '<rootDir>/prisma/generated/schemas.ts',
                '^server-only$': '<rootDir>/tests/__mocks__/server-only.ts',
                '^services/(.*)$': '<rootDir>/src/services/$1',
                '^tests/(.*)$': '<rootDir>/tests/$1',
            },
            modulePaths: ['<rootDir>/src/'],
            setupFilesAfterEnv: ['<rootDir>/jest.setup.frontend.ts'],
            testEnvironment: 'jsdom',
            testMatch: ['<rootDir>/tests/components/**/*.test.tsx'],
            testPathIgnorePatterns: ['/node_modules/', '/e2e/'],
            transform: {
                '^.+\\.(t|j)sx?$': ['@swc/jest'],
                '^.+\\.css$': 'jest-css-modules-transform'
            },
            transformIgnorePatterns: [
                "node_modules/(?!(nanostores|better-auth|uncrypto|jose|@noble)/)",
            ],
            watchPathIgnorePatterns: [
                "<rootDir>/.git/",
                "<rootDir>/.github/",
                "<rootDir>/.next/",
                "<rootDir>/.vscode/",
                "<rootDir>/build/",
                "<rootDir>/coverage/",
                "<rootDir>/dist/",
                "<rootDir>/node_modules/",
                "<rootDir>/out/",
                "<rootDir>/src/tests/api/",
                "<rootDir>/src/tests/services/",
            ],
        },
    ],
};
