
import type { Mock } from 'vitest';
import { vi } from 'vitest';

import playerRecordService from '@/services/PlayerRecord';
vi.mock('services/PlayerRecord');

export const mockTable = [
    {
        "year": 2010,
        "responses": 42,
        "P": 35,
        "W": 23,
        "D": 1,
        "L": 11,
        "points": 70,
        "averages": 2,
        "stalwart": 80,
        "pub": 28,
        "rankPoints": 1,
        "rankAverages": 2,
        "rankAveragesUnqualified": null,
        "rankStalwart": 3,
        "rankSpeedy": 11,
        "rankSpeedyUnqualified": null,
        "rankPub": 3,
        "speedy": 18825,
        "playerId": 49,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 47,
        "P": 31,
        "W": 16,
        "D": 1,
        "L": 14,
        "points": 49,
        "averages": 1.580645161290323,
        "stalwart": 70,
        "pub": 1,
        "rankPoints": 2,
        "rankAverages": 5,
        "rankAveragesUnqualified": null,
        "rankStalwart": 7,
        "rankSpeedy": 12,
        "rankSpeedyUnqualified": null,
        "rankPub": 12,
        "speedy": 23571,
        "playerId": 46,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 46,
        "P": 37,
        "W": 15,
        "D": 2,
        "L": 20,
        "points": 47,
        "averages": 1.27027027027027,
        "stalwart": 84,
        "pub": 27,
        "rankPoints": 3,
        "rankAverages": 11,
        "rankAveragesUnqualified": null,
        "rankStalwart": 1,
        "rankSpeedy": 4,
        "rankSpeedyUnqualified": null,
        "rankPub": 4,
        "speedy": 9865,
        "playerId": 11,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 39,
        "P": 30,
        "W": 15,
        "D": 2,
        "L": 13,
        "points": 47,
        "averages": 1.566666666666667,
        "stalwart": 68,
        "pub": 31,
        "rankPoints": 3,
        "rankAverages": 7,
        "rankAveragesUnqualified": null,
        "rankStalwart": 8,
        "rankSpeedy": 23,
        "rankSpeedyUnqualified": null,
        "rankPub": 2,
        "speedy": 79055,
        "playerId": 14,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 33,
        "P": 26,
        "W": 15,
        "D": 2,
        "L": 9,
        "points": 47,
        "averages": 1.807692307692308,
        "stalwart": 59,
        "pub": null,
        "rankPoints": 3,
        "rankAverages": 4,
        "rankAveragesUnqualified": null,
        "rankStalwart": 9,
        "rankSpeedy": 10,
        "rankSpeedyUnqualified": null,
        "rankPub": null,
        "speedy": 18661,
        "playerId": 30,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 44,
        "P": 36,
        "W": 15,
        "D": 2,
        "L": 19,
        "points": 47,
        "averages": 1.305555555555556,
        "stalwart": 82,
        "pub": null,
        "rankPoints": 3,
        "rankAverages": 10,
        "rankAveragesUnqualified": null,
        "rankStalwart": 2,
        "rankSpeedy": 8,
        "rankSpeedyUnqualified": null,
        "rankPub": null,
        "speedy": 17300,
        "playerId": 62,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 41,
        "P": 33,
        "W": 14,
        "D": 2,
        "L": 17,
        "points": 44,
        "averages": 1.333333333333333,
        "stalwart": 75,
        "pub": 2,
        "rankPoints": 7,
        "rankAverages": 9,
        "rankAveragesUnqualified": null,
        "rankStalwart": 6,
        "rankSpeedy": 15,
        "rankSpeedyUnqualified": null,
        "rankPub": 10,
        "speedy": 35192,
        "playerId": 31,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 39,
        "P": 19,
        "W": 13,
        "D": 2,
        "L": 4,
        "points": 41,
        "averages": 2.157894736842105,
        "stalwart": 43,
        "pub": 1,
        "rankPoints": 8,
        "rankAverages": 1,
        "rankAveragesUnqualified": null,
        "rankStalwart": 12,
        "rankSpeedy": 1,
        "rankSpeedyUnqualified": null,
        "rankPub": 12,
        "speedy": 3108,
        "playerId": 67,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 47,
        "P": 34,
        "W": 13,
        "D": 1,
        "L": 20,
        "points": 40,
        "averages": 1.176470588235294,
        "stalwart": 77,
        "pub": 34,
        "rankPoints": 9,
        "rankAverages": 14,
        "rankAveragesUnqualified": null,
        "rankStalwart": 4,
        "rankSpeedy": 13,
        "rankSpeedyUnqualified": null,
        "rankPub": 1,
        "speedy": 24418,
        "playerId": 12,
        "gameDayId": 461,
    },
    {
        "year": 2010,
        "responses": 42,
        "P": 34,
        "W": 13,
        "D": 1,
        "L": 20,
        "points": 40,
        "averages": 1.176470588235294,
        "stalwart": 77,
        "pub": 2,
        "rankPoints": 9,
        "rankAverages": 14,
        "rankAveragesUnqualified": null,
        "rankStalwart": 4,
        "rankSpeedy": 3,
        "rankSpeedyUnqualified": null,
        "rankPub": 10,
        "speedy": 9131,
        "playerId": 60,
        "gameDayId": 461,
    },
];

export const setupTableMocks = () => {
    beforeEach(() => {
        (playerRecordService.getTable as Mock).mockResolvedValue(mockTable);
    });
};
