-- Migration: Replace ISO codes with FIFA codes in Country and CountrySupporter tables

-- Step 1: Add fifaCode column to Country (nullable initially)
ALTER TABLE `Country` ADD COLUMN `fifaCode` VARCHAR(3) NULL;

-- Step 2: Populate fifaCode from isoCode using ISO -> FIFA mapping
UPDATE `Country` SET `fifaCode` = CASE `isoCode`
  WHEN 'AF' THEN 'AFG'
  WHEN 'AL' THEN 'ALB'
  WHEN 'DZ' THEN 'ALG'
  WHEN 'AS' THEN 'ASA'
  WHEN 'AD' THEN 'AND'
  WHEN 'AO' THEN 'ANG'
  WHEN 'AI' THEN 'AIA'
  WHEN 'AG' THEN 'ATG'
  WHEN 'AR' THEN 'ARG'
  WHEN 'AM' THEN 'ARM'
  WHEN 'AW' THEN 'ARU'
  WHEN 'AU' THEN 'AUS'
  WHEN 'AT' THEN 'AUT'
  WHEN 'AZ' THEN 'AZE'
  WHEN 'BS' THEN 'BAH'
  WHEN 'BH' THEN 'BHR'
  WHEN 'BD' THEN 'BAN'
  WHEN 'BB' THEN 'BRB'
  WHEN 'BY' THEN 'BLR'
  WHEN 'BE' THEN 'BEL'
  WHEN 'BZ' THEN 'BLZ'
  WHEN 'BJ' THEN 'BEN'
  WHEN 'BM' THEN 'BER'
  WHEN 'BT' THEN 'BHU'
  WHEN 'BO' THEN 'BOL'
  WHEN 'BA' THEN 'BIH'
  WHEN 'BW' THEN 'BOT'
  WHEN 'BR' THEN 'BRA'
  WHEN 'VG' THEN 'VGB'
  WHEN 'BN' THEN 'BRU'
  WHEN 'BG' THEN 'BUL'
  WHEN 'BF' THEN 'BFA'
  WHEN 'BI' THEN 'BDI'
  WHEN 'KH' THEN 'CAM'
  WHEN 'CM' THEN 'CMR'
  WHEN 'CA' THEN 'CAN'
  WHEN 'CV' THEN 'CPV'
  WHEN 'KY' THEN 'CAY'
  WHEN 'CF' THEN 'CTA'
  WHEN 'TD' THEN 'CHA'
  WHEN 'CL' THEN 'CHI'
  WHEN 'CN' THEN 'CHN'
  WHEN 'TW' THEN 'TPE'
  WHEN 'CO' THEN 'COL'
  WHEN 'KM' THEN 'COM'
  WHEN 'CG' THEN 'CGO'
  WHEN 'CD' THEN 'COD'
  WHEN 'CI' THEN 'CIV'
  WHEN 'CK' THEN 'COK'
  WHEN 'CR' THEN 'CRC'
  WHEN 'CU' THEN 'CUB'
  WHEN 'CW' THEN 'CUW'
  WHEN 'CY' THEN 'CYP'
  WHEN 'CZ' THEN 'CZE'
  WHEN 'DK' THEN 'DEN'
  WHEN 'DJ' THEN 'DJI'
  WHEN 'DM' THEN 'DMA'
  WHEN 'DO' THEN 'DOM'
  WHEN 'EC' THEN 'ECU'
  WHEN 'EG' THEN 'EGY'
  WHEN 'SV' THEN 'SLV'
  WHEN 'GB-ENG' THEN 'ENG'
  WHEN 'GQ' THEN 'EQG'
  WHEN 'ER' THEN 'ERI'
  WHEN 'EE' THEN 'EST'
  WHEN 'ET' THEN 'ETH'
  WHEN 'FO' THEN 'FRO'
  WHEN 'FJ' THEN 'FIJ'
  WHEN 'FI' THEN 'FIN'
  WHEN 'FR' THEN 'FRA'
  WHEN 'GA' THEN 'GAB'
  WHEN 'GM' THEN 'GAM'
  WHEN 'GE' THEN 'GEO'
  WHEN 'DE' THEN 'GER'
  WHEN 'GH' THEN 'GHA'
  WHEN 'GI' THEN 'GIB'
  WHEN 'GR' THEN 'GRE'
  WHEN 'GD' THEN 'GRN'
  WHEN 'GU' THEN 'GUM'
  WHEN 'GT' THEN 'GUA'
  WHEN 'GN' THEN 'GUI'
  WHEN 'GW' THEN 'GNB'
  WHEN 'GY' THEN 'GUY'
  WHEN 'HT' THEN 'HAI'
  WHEN 'HN' THEN 'HON'
  WHEN 'HK' THEN 'HKG'
  WHEN 'HR' THEN 'CRO'
  WHEN 'HU' THEN 'HUN'
  WHEN 'IS' THEN 'ISL'
  WHEN 'IN' THEN 'IND'
  WHEN 'ID' THEN 'IDN'
  WHEN 'IR' THEN 'IRN'
  WHEN 'IQ' THEN 'IRQ'
  WHEN 'IL' THEN 'ISR'
  WHEN 'IT' THEN 'ITA'
  WHEN 'JM' THEN 'JAM'
  WHEN 'JP' THEN 'JPN'
  WHEN 'JO' THEN 'JOR'
  WHEN 'KZ' THEN 'KAZ'
  WHEN 'KE' THEN 'KEN'
  WHEN 'XK' THEN 'KVX'
  WHEN 'KW' THEN 'KUW'
  WHEN 'KG' THEN 'KGZ'
  WHEN 'LA' THEN 'LAO'
  WHEN 'LV' THEN 'LVA'
  WHEN 'LB' THEN 'LBN'
  WHEN 'LS' THEN 'LES'
  WHEN 'LR' THEN 'LBR'
  WHEN 'LY' THEN 'LBY'
  WHEN 'LI' THEN 'LIE'
  WHEN 'LT' THEN 'LTU'
  WHEN 'LU' THEN 'LUX'
  WHEN 'MO' THEN 'MAC'
  WHEN 'MG' THEN 'MAD'
  WHEN 'MW' THEN 'MWI'
  WHEN 'MY' THEN 'MAS'
  WHEN 'MV' THEN 'MDV'
  WHEN 'ML' THEN 'MLI'
  WHEN 'MT' THEN 'MLT'
  WHEN 'MR' THEN 'MTN'
  WHEN 'MU' THEN 'MRI'
  WHEN 'MX' THEN 'MEX'
  WHEN 'MD' THEN 'MDA'
  WHEN 'MN' THEN 'MGL'
  WHEN 'ME' THEN 'MNE'
  WHEN 'MS' THEN 'MSR'
  WHEN 'MA' THEN 'MAR'
  WHEN 'MZ' THEN 'MOZ'
  WHEN 'MM' THEN 'MYA'
  WHEN 'NA' THEN 'NAM'
  WHEN 'NP' THEN 'NEP'
  WHEN 'NL' THEN 'NED'
  WHEN 'NC' THEN 'NCL'
  WHEN 'NZ' THEN 'NZL'
  WHEN 'NI' THEN 'NCA'
  WHEN 'NE' THEN 'NIG'
  WHEN 'NG' THEN 'NGA'
  WHEN 'KP' THEN 'PRK'
  WHEN 'MK' THEN 'MKD'
  WHEN 'GB-NIR' THEN 'NIR'
  WHEN 'NO' THEN 'NOR'
  WHEN 'OM' THEN 'OMA'
  WHEN 'PK' THEN 'PAK'
  WHEN 'PS' THEN 'PLE'
  WHEN 'PA' THEN 'PAN'
  WHEN 'PG' THEN 'PNG'
  WHEN 'PY' THEN 'PAR'
  WHEN 'PE' THEN 'PER'
  WHEN 'PH' THEN 'PHI'
  WHEN 'PL' THEN 'POL'
  WHEN 'PT' THEN 'POR'
  WHEN 'PR' THEN 'PUR'
  WHEN 'QA' THEN 'QAT'
  WHEN 'IE' THEN 'IRL'
  WHEN 'RO' THEN 'ROU'
  WHEN 'RU' THEN 'RUS'
  WHEN 'RW' THEN 'RWA'
  WHEN 'KN' THEN 'SKN'
  WHEN 'LC' THEN 'LCA'
  WHEN 'VC' THEN 'VIN'
  WHEN 'WS' THEN 'SAM'
  WHEN 'SM' THEN 'SMR'
  WHEN 'ST' THEN 'STP'
  WHEN 'SA' THEN 'KSA'
  WHEN 'GB-SCT' THEN 'SCO'
  WHEN 'SN' THEN 'SEN'
  WHEN 'RS' THEN 'SRB'
  WHEN 'SC' THEN 'SEY'
  WHEN 'SL' THEN 'SLE'
  WHEN 'SG' THEN 'SGP'
  WHEN 'SK' THEN 'SVK'
  WHEN 'SI' THEN 'SVN'
  WHEN 'SB' THEN 'SOL'
  WHEN 'SO' THEN 'SOM'
  WHEN 'ZA' THEN 'RSA'
  WHEN 'KR' THEN 'KOR'
  WHEN 'SS' THEN 'SSD'
  WHEN 'ES' THEN 'ESP'
  WHEN 'LK' THEN 'SRI'
  WHEN 'SD' THEN 'SDN'
  WHEN 'SR' THEN 'SUR'
  WHEN 'SE' THEN 'SWE'
  WHEN 'SZ' THEN 'SWZ'
  WHEN 'CH' THEN 'SUI'
  WHEN 'SY' THEN 'SYR'
  WHEN 'PF' THEN 'TAH'
  WHEN 'TJ' THEN 'TJK'
  WHEN 'TZ' THEN 'TAN'
  WHEN 'TH' THEN 'THA'
  WHEN 'TG' THEN 'TOG'
  WHEN 'TO' THEN 'TGA'
  WHEN 'TT' THEN 'TRI'
  WHEN 'TN' THEN 'TUN'
  WHEN 'TR' THEN 'TUR'
  WHEN 'TL' THEN 'TLS'
  WHEN 'TM' THEN 'TKM'
  WHEN 'TC' THEN 'TCA'
  WHEN 'UG' THEN 'UGA'
  WHEN 'UA' THEN 'UKR'
  WHEN 'AE' THEN 'UAE'
  WHEN 'US' THEN 'USA'
  WHEN 'UY' THEN 'URU'
  WHEN 'VI' THEN 'VIR'
  WHEN 'UZ' THEN 'UZB'
  WHEN 'VU' THEN 'VAN'
  WHEN 'VE' THEN 'VEN'
  WHEN 'VN' THEN 'VIE'
  WHEN 'GB-WLS' THEN 'WAL'
  WHEN 'YE' THEN 'YEM'
  WHEN 'ZM' THEN 'ZAM'
  WHEN 'ZW' THEN 'ZIM'
  ELSE NULL
END;

-- Step 3: Drop CountrySupporter rows whose country has no FIFA code mapping
DELETE FROM `CountrySupporter`
WHERE `countryISOCode` IN (SELECT `isoCode` FROM `Country` WHERE `fifaCode` IS NULL);

-- Step 4: Drop Country rows with no FIFA code mapping
DELETE FROM `Country` WHERE `fifaCode` IS NULL;

-- Step 5: Add countryFIFACode to CountrySupporter (nullable initially)
ALTER TABLE `CountrySupporter` ADD COLUMN `countryFIFACode` VARCHAR(3) NULL;

-- Step 6: Populate countryFIFACode from the Country table mapping
UPDATE `CountrySupporter` cs
JOIN `Country` c ON cs.`countryISOCode` = c.`isoCode`
SET cs.`countryFIFACode` = c.`fifaCode`;

-- Step 7: Drop old unique index and index on CountrySupporter before altering columns
DROP INDEX `CountrySupporter_playerId_countryISOCode_key` ON `CountrySupporter`;
DROP INDEX `CountrySupporter_countryISOCode_idx` ON `CountrySupporter`;

-- Step 8: Drop the old isoCode primary key and set fifaCode as the new PK
ALTER TABLE `Country` DROP PRIMARY KEY;
ALTER TABLE `Country` MODIFY `fifaCode` VARCHAR(3) NOT NULL, ADD PRIMARY KEY (`fifaCode`);

-- Step 9: Make countryFIFACode NOT NULL and drop countryISOCode
ALTER TABLE `CountrySupporter` MODIFY `countryFIFACode` VARCHAR(3) NOT NULL;
ALTER TABLE `CountrySupporter` DROP COLUMN `countryISOCode`;

-- Step 10: Drop the old isoCode column from Country
ALTER TABLE `Country` DROP COLUMN `isoCode`;

-- Step 11: Recreate indexes on CountrySupporter with new column name
CREATE INDEX `CountrySupporter_countryFIFACode_idx` ON `CountrySupporter`(`countryFIFACode`);
CREATE UNIQUE INDEX `CountrySupporter_playerId_countryFIFACode_key` ON `CountrySupporter`(`playerId`, `countryFIFACode`);
