docker buildx build \
    --secret id=DATABASE_URL,env=DATABASE_URL \
    --secret id=AZURE_CLIENT_ID,env=AZURE_CLIENT_ID \
    --secret id=AZURE_CLIENT_SECRET,env=AZURE_CLIENT_SECRET \
    --secret id=AZURE_CONTAINER_NAME,env=AZURE_CONTAINER_NAME \
    --secret id=AZURE_STORAGE_ACCOUNT_NAME,env=AZURE_STORAGE_ACCOUNT_NAME \
    --secret id=AZURE_SUBSCRIPTION_ID,env=AZURE_SUBSCRIPTION_ID \
    --secret id=AZURE_TENANT_ID,env=AZURE_TENANT_ID \
    --secret id=BETTER_AUTH_SECRET,env=BETTER_AUTH_SECRET \
    --secret id=BETTER_AUTH_URL,env=BETTER_AUTH_URL \
    --secret id=GOOGLE_CLIENT_ID,env=GOOGLE_CLIENT_ID \
    --secret id=GOOGLE_CLIENT_SECRET,env=GOOGLE_CLIENT_SECRET \
    --secret id=MICROSOFT_CLIENT_ID,env=MICROSOFT_CLIENT_ID \
    --secret id=MICROSOFT_CLIENT_SECRET,env=MICROSOFT_CLIENT_SECRET \
    --secret id=MYSQL_ROOT_PASSWORD,env=MYSQL_ROOT_PASSWORD \
    --secret id=SENTRY_AUTH_TOKEN,env=SENTRY_AUTH_TOKEN \
    .
