docker buildx build \
    --build-arg DATABASE_URL=${DATABASE_URL} \
    --build-arg AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
    --build-arg AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} \
    --build-arg AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME} \
    --build-arg AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME} \
    --build-arg AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} \
    --build-arg AZURE_TENANT_ID=${AZURE_TENANT_ID} \
    --build-arg BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET} \
    --build-arg BETTER_AUTH_URL=${BETTER_AUTH_URL} \
    --build-arg GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    --build-arg GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    --build-arg MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID} \
    --build-arg MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET} \
    --build-arg DATABASE_PASSWORD=${DATABASE_PASSWORD} \
    --build-arg SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN} \
    --load \
    -t next-www-toastboy:latest \
    .
