docker buildx build \
    --build-arg DATABASE_URL=${DATABASE_URL} \
    --build-arg STORAGE_CLIENT_ID=${STORAGE_CLIENT_ID} \
    --build-arg STORAGE_CLIENT_SECRET=${STORAGE_CLIENT_SECRET} \
    --build-arg AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME} \
    --build-arg AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME} \
    --build-arg AZURE_TENANT_ID=${AZURE_TENANT_ID} \
    --build-arg BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET} \
    --build-arg BETTER_AUTH_URL=${BETTER_AUTH_URL} \
    --build-arg AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID} \
    --build-arg AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET} \
    --build-arg AUTH_MICROSOFT_CLIENT_ID=${AUTH_MICROSOFT_CLIENT_ID} \
    --build-arg AUTH_MICROSOFT_CLIENT_SECRET=${AUTH_MICROSOFT_CLIENT_SECRET} \
    --build-arg DATABASE_PASSWORD=${DATABASE_PASSWORD} \
    --build-arg SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN} \
    --load \
    -t next-www-toastboy:latest \
    .
