-- Migration: Fix mojibake (UTF-8 read as Windows-1252) in Club.clubName
-- 108 affected rows across: argentina, austria, belgium, brazil, croatia, cuba,
-- czech-republic, denmark, ecuador, estonia, finland, france, germany, hungary,
-- luxembourg, portugal, slovakia, spain, sweden, switzerland, turkey
-- Strategy: re-encode each corrupted string from cp1252 bytes back to correct UTF-8

UPDATE `Club` SET `clubName` = 'Ctro. Español' WHERE id = 190; -- was: 'Ctro. EspaÃ±ol'
UPDATE `Club` SET `clubName` = 'Est. Río Cuarto' WHERE id = 209; -- was: 'Est. RÃ\xado Cuarto'
UPDATE `Club` SET `clubName` = 'Admira Wacker Mödling' WHERE id = 383; -- was: 'Admira Wacker MÃ¶dling'
UPDATE `Club` SET `clubName` = 'FAC Team für Wien' WHERE id = 395; -- was: 'FAC Team fÃ¼r Wien'
UPDATE `Club` SET `clubName` = 'FC Höchst' WHERE id = 399; -- was: 'FC HÃ¶chst'
UPDATE `Club` SET `clubName` = 'FC Kärnten Klagenfurt' WHERE id = 401; -- was: 'FC KÃ¤rnten Klagenfurt'
UPDATE `Club` SET `clubName` = 'FC Vöcklabruck' WHERE id = 403; -- was: 'FC VÃ¶cklabruck'
UPDATE `Club` SET `clubName` = 'SKN St Pölten' WHERE id = 436; -- was: 'SKN St PÃ¶lten'
UPDATE `Club` SET `clubName` = 'SPG Axams Götzens' WHERE id = 437; -- was: 'SPG Axams GÃ¶tzens'
UPDATE `Club` SET `clubName` = 'SV Grödig' WHERE id = 444; -- was: 'SV GrÃ¶dig'
UPDATE `Club` SET `clubName` = 'SV Würmla' WHERE id = 456; -- was: 'SV WÃ¼rmla'
UPDATE `Club` SET `clubName` = 'WAC St Andrä' WHERE id = 466; -- was: 'WAC St AndrÃ¤'
UPDATE `Club` SET `clubName` = 'RFC Sérésien' WHERE id = 730; -- was: 'RFC SÃ©rÃ©sien'
UPDATE `Club` SET `clubName` = 'Standard de Liège' WHERE id = 756; -- was: 'Standard de LiÃ¨ge'
UPDATE `Club` SET `clubName` = 'Caiçara/PI' WHERE id = 948; -- was: 'CaiÃ§ara/PI'
UPDATE `Club` SET `clubName` = 'Camaçariense/BA' WHERE id = 951; -- was: 'CamaÃ§ariense/BA'
UPDATE `Club` SET `clubName` = 'Confiança/SE' WHERE id = 981; -- was: 'ConfianÃ§a/SE'
UPDATE `Club` SET `clubName` = 'Cuiabá/MT' WHERE id = 1002; -- was: 'CuiabÃ¡/MT'
UPDATE `Club` SET `clubName` = 'Redenção/Pa' WHERE id = 1193; -- was: 'RedenÃ§Ã£o/Pa'
UPDATE `Club` SET `clubName` = 'Santa Inês/MA' WHERE id = 1219; -- was: 'Santa InÃªs/MA'
UPDATE `Club` SET `clubName` = 'Rudeš' WHERE id = 1676; -- was: 'RudeÅ¡'
UPDATE `Club` SET `clubName` = 'Camagüey' WHERE id = 1703; -- was: 'CamagÃ¼ey'
UPDATE `Club` SET `clubName` = 'Ciego de Ávila' WHERE id = 1704; -- was: 'Ciego de Ã\x81vila'
UPDATE `Club` SET `clubName` = 'Guantánamo' WHERE id = 1707; -- was: 'GuantÃ¡namo'
UPDATE `Club` SET `clubName` = 'Holguín' WHERE id = 1708; -- was: 'HolguÃ\xadn'
UPDATE `Club` SET `clubName` = 'Pinar del Río' WHERE id = 1714; -- was: 'Pinar del RÃ\xado'
UPDATE `Club` SET `clubName` = 'Sancti Spíritus' WHERE id = 1715; -- was: 'Sancti SpÃ\xadritus'
UPDATE `Club` SET `clubName` = 'Sokol Ovcáry' WHERE id = 1854; -- was: 'Sokol OvcÃ¡ry'
UPDATE `Club` SET `clubName` = 'BK Søllerød Vedbaek' WHERE id = 1890; -- was: 'BK SÃ¸llerÃ¸d Vedbaek'
UPDATE `Club` SET `clubName` = 'Brøndby IF' WHERE id = 1892; -- was: 'BrÃ¸ndby IF'
UPDATE `Club` SET `clubName` = 'Brøndby IF II' WHERE id = 1893; -- was: 'BrÃ¸ndby IF II'
UPDATE `Club` SET `clubName` = 'Brønshøj BK' WHERE id = 1894; -- was: 'BrÃ¸nshÃ¸j BK'
UPDATE `Club` SET `clubName` = 'Herfølge BK' WHERE id = 1913; -- was: 'HerfÃ¸lge BK'
UPDATE `Club` SET `clubName` = 'Hjørring IF' WHERE id = 1916; -- was: 'HjÃ¸rring IF'
UPDATE `Club` SET `clubName` = 'Køge BK' WHERE id = 1928; -- was: 'KÃ¸ge BK'
UPDATE `Club` SET `clubName` = 'Sorø IF Freja' WHERE id = 1944; -- was: 'SorÃ¸ IF Freja'
UPDATE `Club` SET `clubName` = 'Stenløse BK' WHERE id = 1945; -- was: 'StenlÃ¸se BK'
UPDATE `Club` SET `clubName` = 'SønderjyskE Haderslev' WHERE id = 1947; -- was: 'SÃ¸nderjyskE Haderslev'
UPDATE `Club` SET `clubName` = 'Vanløse IF' WHERE id = 1949; -- was: 'VanlÃ¸se IF'
UPDATE `Club` SET `clubName` = 'Værløse BK' WHERE id = 1954; -- was: 'VÃ¦rlÃ¸se BK'
UPDATE `Club` SET `clubName` = 'Ølstykke FC' WHERE id = 1955; -- was: 'Ã˜lstykke FC'
UPDATE `Club` SET `clubName` = 'Østerbro' WHERE id = 1956; -- was: 'Ã˜sterbro'
UPDATE `Club` SET `clubName` = 'Municipal Cañar' WHERE id = 1983; -- was: 'Municipal CaÃ±ar'
UPDATE `Club` SET `clubName` = 'Sörve' WHERE id = 2467; -- was: 'SÃ¶rve'
UPDATE `Club` SET `clubName` = 'JäPS' WHERE id = 2567; -- was: 'JÃ¤PS'
UPDATE `Club` SET `clubName` = 'Kaskö' WHERE id = 2575; -- was: 'KaskÃ¶'
UPDATE `Club` SET `clubName` = 'SäyRi' WHERE id = 2651; -- was: 'SÃ¤yRi'
UPDATE `Club` SET `clubName` = 'Virkiä' WHERE id = 2669; -- was: 'VirkiÃ¤'
UPDATE `Club` SET `clubName` = 'Öja-73' WHERE id = 2678; -- was: 'Ã–ja-73'
UPDATE `Club` SET `clubName` = 'FC Sète 34' WHERE id = 2798; -- was: 'FC SÃ¨te 34'
UPDATE `Club` SET `clubName` = 'SO Châtellerault' WHERE id = 2893; -- was: 'SO ChÃ¢tellerault'
UPDATE `Club` SET `clubName` = 'US Créteil' WHERE id = 2938; -- was: 'US CrÃ©teil'
UPDATE `Club` SET `clubName` = 'Bayern München' WHERE id = 3022; -- was: 'Bayern MÃ¼nchen'
UPDATE `Club` SET `clubName` = 'Bayern München II' WHERE id = 3023; -- was: 'Bayern MÃ¼nchen II'
UPDATE `Club` SET `clubName` = 'Borussia Mönchengladbach' WHERE id = 3032; -- was: 'Borussia MÃ¶nchengladbach'
UPDATE `Club` SET `clubName` = 'Borussia Mönchengladbach II' WHERE id = 3033; -- was: 'Borussia MÃ¶nchengladbach II'
UPDATE `Club` SET `clubName` = 'FC Köln' WHERE id = 3086; -- was: 'FC KÃ¶ln'
UPDATE `Club` SET `clubName` = 'FC Nürnberg' WHERE id = 3091; -- was: 'FC NÃ¼rnberg'
UPDATE `Club` SET `clubName` = 'FC Saarbrücken' WHERE id = 3095; -- was: 'FC SaarbrÃ¼cken'
UPDATE `Club` SET `clubName` = 'Fortuna Düsseldorf' WHERE id = 3104; -- was: 'Fortuna DÃ¼sseldorf'
UPDATE `Club` SET `clubName` = 'Greuther Fürth' WHERE id = 3126; -- was: 'Greuther FÃ¼rth'
UPDATE `Club` SET `clubName` = 'Normannia Gmünd' WHERE id = 3169; -- was: 'Normannia GmÃ¼nd'
UPDATE `Club` SET `clubName` = 'RSV Würges' WHERE id = 3185; -- was: 'RSV WÃ¼rges'
UPDATE `Club` SET `clubName` = 'TSG Wörsdorf' WHERE id = 3261; -- was: 'TSG WÃ¶rsdorf'
UPDATE `Club` SET `clubName` = 'TSV 1860 München' WHERE id = 3262; -- was: 'TSV 1860 MÃ¼nchen'
UPDATE `Club` SET `clubName` = 'TSV 1860 München II' WHERE id = 3263; -- was: 'TSV 1860 MÃ¼nchen II'
UPDATE `Club` SET `clubName` = 'VfB Lübeck' WHERE id = 3284; -- was: 'VfB LÃ¼beck'
UPDATE `Club` SET `clubName` = 'VfL Osnabrück' WHERE id = 3297; -- was: 'VfL OsnabrÃ¼ck'
UPDATE `Club` SET `clubName` = 'Würzburger FV' WHERE id = 3318; -- was: 'WÃ¼rzburger FV'
UPDATE `Club` SET `clubName` = 'BFC Siófok' WHERE id = 3541; -- was: 'BFC SiÃ³fok'
UPDATE `Club` SET `clubName` = 'Diósgyöri VTK Miskolc' WHERE id = 3561; -- was: 'DiÃ³sgyÃ¶ri VTK Miskolc'
UPDATE `Club` SET `clubName` = 'FC Fehérvár' WHERE id = 3567; -- was: 'FC FehÃ©rvÃ¡r'
UPDATE `Club` SET `clubName` = 'Györ ETO FC' WHERE id = 3574; -- was: 'GyÃ¶r ETO FC'
UPDATE `Club` SET `clubName` = 'Nyíregyháza Spartacus' WHERE id = 3594; -- was: 'NyÃ\xadregyhÃ¡za Spartacus'
UPDATE `Club` SET `clubName` = 'Pécsi MFC' WHERE id = 3597; -- was: 'PÃ©csi MFC'
UPDATE `Club` SET `clubName` = 'Etzella Ettelbrück' WHERE id = 4514; -- was: 'Etzella EttelbrÃ¼ck'
UPDATE `Club` SET `clubName` = 'Leixões Matosinhos' WHERE id = 5583; -- was: 'LeixÃµes Matosinhos'
UPDATE `Club` SET `clubName` = 'Paços de Ferreira' WHERE id = 5609; -- was: 'PaÃ§os de Ferreira'
UPDATE `Club` SET `clubName` = 'Dukla Banská Bystrica' WHERE id = 6363; -- was: 'Dukla BanskÃ¡ Bystrica'
UPDATE `Club` SET `clubName` = 'FC ViOn Zlaté Moravce' WHERE id = 6367; -- was: 'FC ViOn ZlatÃ© Moravce'
UPDATE `Club` SET `clubName` = 'FKS Nemšová' WHERE id = 6370; -- was: 'FKS NemÅ¡ovÃ¡'
UPDATE `Club` SET `clubName` = 'AD Cerro del Águila' WHERE id = 6518; -- was: 'AD Cerro del Ã\x81guila'
UPDATE `Club` SET `clubName` = 'CD Cala d´Or' WHERE id = 6625; -- was: 'CD Cala dÂ´Or'
UPDATE `Club` SET `clubName` = 'Deportivo Alavés' WHERE id = 6787; -- was: 'Deportivo AlavÃ©s'
UPDATE `Club` SET `clubName` = 'Deportivo La Coruña' WHERE id = 6789; -- was: 'Deportivo La CoruÃ±a'
UPDATE `Club` SET `clubName` = 'Real Sporting de Gijón' WHERE id = 6897; -- was: 'Real Sporting de GijÃ³n'
UPDATE `Club` SET `clubName` = 'Real Sporting de Gijón II' WHERE id = 6898; -- was: 'Real Sporting de GijÃ³n II'
UPDATE `Club` SET `clubName` = 'Hertzöga' WHERE id = 7124; -- was: 'HertzÃ¶ga'
UPDATE `Club` SET `clubName` = 'IF Sylvia Norrköping' WHERE id = 7132; -- was: 'IF Sylvia NorrkÃ¶ping'
UPDATE `Club` SET `clubName` = 'Kongahälla' WHERE id = 7163; -- was: 'KongahÃ¤lla'
UPDATE `Club` SET `clubName` = 'FC Hägendorf' WHERE id = 7283; -- was: 'FC HÃ¤gendorf'
UPDATE `Club` SET `clubName` = 'FC Küsnacht' WHERE id = 7285; -- was: 'FC KÃ¼snacht'
UPDATE `Club` SET `clubName` = 'FC Léchelles' WHERE id = 7292; -- was: 'FC LÃ©chelles'
UPDATE `Club` SET `clubName` = 'FC Münsingen' WHERE id = 7301; -- was: 'FC MÃ¼nsingen'
UPDATE `Club` SET `clubName` = 'FC Red Star Zürich' WHERE id = 7307; -- was: 'FC Red Star ZÃ¼rich'
UPDATE `Club` SET `clubName` = 'FC Savièse' WHERE id = 7309; -- was: 'FC SaviÃ¨se'
UPDATE `Club` SET `clubName` = 'FC Schötz' WHERE id = 7311; -- was: 'FC SchÃ¶tz'
UPDATE `Club` SET `clubName` = 'FC Serrières Neuchatel' WHERE id = 7313; -- was: 'FC SerriÃ¨res Neuchatel'
UPDATE `Club` SET `clubName` = 'FC Töss Winterthur' WHERE id = 7321; -- was: 'FC TÃ¶ss Winterthur'
UPDATE `Club` SET `clubName` = 'FC Zürich' WHERE id = 7332; -- was: 'FC ZÃ¼rich'
UPDATE `Club` SET `clubName` = 'FC Zürich II' WHERE id = 7333; -- was: 'FC ZÃ¼rich II'
UPDATE `Club` SET `clubName` = 'Grasshoppers Zürich II' WHERE id = 7336; -- was: 'Grasshoppers ZÃ¼rich II'
UPDATE `Club` SET `clubName` = 'SC Brühl St Gallen' WHERE id = 7342; -- was: 'SC BrÃ¼hl St Gallen'
UPDATE `Club` SET `clubName` = 'SC Düdingen' WHERE id = 7344; -- was: 'SC DÃ¼dingen'
UPDATE `Club` SET `clubName` = 'SC YF Juventus Zürich' WHERE id = 7346; -- was: 'SC YF Juventus ZÃ¼rich'
UPDATE `Club` SET `clubName` = 'Fenerbahçe Istanbul' WHERE id = 7460; -- was: 'FenerbahÃ§e Istanbul'
UPDATE `Club` SET `clubName` = 'Gençlerbirligi Ankara' WHERE id = 7468; -- was: 'GenÃ§lerbirligi Ankara'
UPDATE `Club` SET `clubName` = 'MKE Ankaragücü' WHERE id = 7497; -- was: 'MKE AnkaragÃ¼cÃ¼'