import { handleGET } from 'lib/api';
import { NextRequest } from 'next/server';
import outcomeService from 'services/Outcome';

/**
 * Handles the GET request for the turnout API endpoint.
 *
 * @param request - The incoming Next.js request object.
 * @param props - An object containing route parameters.
 * @param props.params - A promise resolving to a record of route parameters.
 * @returns A response object generated by the `handleGET` function.
 */
export const GET = async (request: NextRequest, props: { params: Promise<Record<string, string>> }) => {
    const params = await props.params;
    return handleGET(
        () => outcomeService.getTurnout(),
        { params },
    );
};
