import { handleGET } from "lib/api";
import { NextRequest } from "next/server";
import countryService from "services/Country";

/**
 * Handles GET requests for retrieving country information based on the provided ISO code.
 *
 * @param request - The incoming Next.js request object.
 * @param props - An object containing route parameters.
 * @param props.params - A promise resolving to a record of route parameters, including the `isoCode`.
 * @returns A response object generated by the `handleGET` function, containing the country data.
 */
export const GET = async (request: NextRequest, props: { params: Promise<Record<string, string>> }) => {
    const params = await props.params;
    return handleGET(
        () => countryService.get(params.isoCode),
        { params },
    );
};
