name: Terraform

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
  TF_PLUGIN_CACHE_DIR: .terraform.d/plugin-cache

  OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
  OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
  TF_VAR_onepassword_connect_host: ${{ secrets.OP_CONNECT_HOST }}
  TF_VAR_onepassword_connect_token: ${{ secrets.OP_CONNECT_TOKEN }}

  TF_VAR_github_repository: '"${{ github.repository }}"'
  TF_VAR_github_run_id: '"${{ github.run_id }}"'
  TF_VAR_github_server_url: '"${{ github.server_url }}"'
  TF_VAR_github_sha: '"${{ github.sha }}"'

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Terraform plugin dir
        uses: actions/cache@v4
        with:
          path: plugin-cache
          key: tf-plugins-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            tf-plugins-${{ runner.os }}-

      - name: Load secrets from 1Password and export to environment
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          TF_VAR_azure_tenant_id: op://next-www-toastboy/TF_AZURE_TENANT_ID/Section_elpyzkswpwjdt45ytdpuj4zpri/uuid
          TF_VAR_azure_subscription_id: op://next-www-toastboy/AZURE_SUBSCRIPTION_ID/Section_u2slseexl7iz6qq3ab3kwfut5u/uuid
          TF_VAR_azure_client_id: op://next-www-toastboy/TF_AZURE_CLIENT_ID/Section_sbgupoixcvisaemyfdnssgod3u/uuid
          TF_VAR_azure_client_secret: op://next-www-toastboy/TF_AZURE_CLIENT_SECRET/Section_al3t4lplsritwudt5bbhjxh4e4/uuid

      - name: Terraform Plan (PRs)
        if: github.event_name == 'pull_request'
        uses: dflook/terraform-plan@v1
        with:
          path: .
          workspace: tf-cloudflare

      - name: Terraform Apply (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: dflook/terraform-apply@v1
        with:
          path: .
          workspace: tf-cloudflare
          auto_approve: true
