name: "Terraform Apply"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "toastboy"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "next-www-toastboy"
  CONFIG_DIRECTORY: "./terraform"

  TF_VAR_github_repository: '"${{ github.repository }}"'
  TF_VAR_github_run_id: '"${{ github.run_id }}"'
  TF_VAR_github_server_url: '"${{ github.server_url }}"'
  TF_VAR_github_sha: '"${{ github.sha }}"'

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      # so GitHub can check out this repo using the default github.token
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load secrets from 1Password and export to environment
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TF_VAR_azure_tenant_id: op://next-www-toastboy/AZURE_TENANT_ID/Section_ylvm7oce47qvgs6ntrhrja2mbm/uuid
          TF_VAR_azure_subscription_id: op://next-www-toastboy/AZURE_SUBSCRIPTION_ID/Section_u2slseexl7iz6qq3ab3kwfut5u/uuid
          TF_VAR_azure_client_id: op://next-www-toastboy/AZURE_CLIENT_ID/Section_ueteoth5u6psueairn64jkyfvq/uuid
          TF_VAR_azure_client_secret: op://next-www-toastboy/AZURE_CLIENT_SECRET/Section_ozdki26oyupp5sforj3idf6v6e/secret

      - name: Escape Terraform secrets as JSON-safe
        run: |
          echo "TF_VAR_azure_tenant_id=$(jq -Rs . <<< \"$TF_VAR_azure_tenant_id\")" >> $GITHUB_ENV
          echo "TF_VAR_azure_subscription_id=$(jq -Rs . <<< \"$TF_VAR_azure_subscription_id\")" >> $GITHUB_ENV
          echo "TF_VAR_azure_client_id=$(jq -Rs . <<< \"$TF_VAR_azure_client_id\")" >> $GITHUB_ENV
          echo "TF_VAR_azure_client_secret=$(jq -Rs . <<< \"$TF_VAR_azure_client_secret\")" >> $GITHUB_ENV

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          token: ${{ secrets.TF_API_TOKEN }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
